import { Dimensions, StyleSheet } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: "#fff",
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  backButton: {
    padding: 8,
  },
  headerText: {
    fontSize: 20,
    color: "#000",
    fontWeight: "bold",
  },
  headerButtons: {
    flexDirection: "row",
  },
  headerButton: {
    padding: 8,
    marginLeft: 15,
  },
  questionContainer: {
    width: width,
    padding: 20,
    alignItems: "center",
  },
  listeningContainer: {
    width: "100%",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    marginBottom: 20,
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  audioControls: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
  },


  questionBox: {
    width: "100%",
    padding: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 5,
    marginBottom: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  tokenContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  imageContainer: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    padding: 10,
    borderRadius: 15,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    marginTop: 15,
  },
  questionImage: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginTop: 15,
  },
  answersContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 10,
  },
  answerButton: {
    width: "85%",
    paddingVertical: 15,
    borderRadius: 5,
    marginBottom: 10,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
  },
  answerText: {
    fontSize: 18,
    color: "#34495E",
    fontWeight: "500",
  },
  explanationButton: {
    paddingVertical: 15,
    paddingHorizontal: 30,
    backgroundColor: "#e3edaf",
    borderRadius: 30,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    width: "70%",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginTop: 10,
  },
  explanationButtonText: {
    color: "#333",
    fontSize: 18,
    fontWeight: "900",
  },
  bottomModal: {
    justifyContent: "flex-end",
    margin: 0,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    padding: 25,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    minHeight: "35%",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
  },
  modalTitle: {
    fontSize: 24,
    marginBottom: 15,
    fontWeight: "700",
    color: "#2C3E50",
    textAlign: "center",
  },
  modalText: {
    fontSize: 18,
    color: "#333333",
  },
  closeButton: {
    marginTop: 10,
    paddingVertical: 12,
    paddingHorizontal: 30,
    backgroundColor: "#2C8D81",
    borderRadius: 25,
    alignItems: "center",
    width: "60%",
  },
  closeButtonText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 25,
    backgroundColor: "#EFEFEF",
  },
  errorText: {
    color: "#D32F2F",
    fontSize: 18,
    textAlign: "center",
    marginBottom: 25,
  },
  retryButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
  },
  retryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  paperModalContainer: {
    backgroundColor: "#ffffff",
    padding: 20,
    margin: 20,
    borderRadius: 20,
    maxHeight: "80%",
  },
  wordTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#4CAF50",
    textAlign: "center",
    marginBottom: 10,
  },
  phoneticText: {
    fontSize: 18,
    color: "#607D8B",
    textAlign: "center",
    fontStyle: "italic",
    marginBottom: 10,
  },
  meanText: {
    fontSize: 18,
    color: "#333333",
    marginBottom: 10,
  },
  meanHighlight: {
    fontWeight: "bold",
    color: "#FF9800",
  },
  exampleContainer: {
    backgroundColor: "#E3F2FD",
    padding: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderLeftWidth: 5,
    borderLeftColor: "#42A5F5",
  },
  exampleTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1E88E5",
    marginBottom: 5,
  },
  exampleMean: {
    fontSize: 14,
    color: "#424242",
  },
  paperTextInput: {
    width: "100%",
    marginBottom: 20,
  },
  paperModalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  paperSaveButton: {
    flex: 1,
    marginRight: 10,
    backgroundColor: "#4CAF50",
  },
  paperCancelButton: {
    flex: 1,
    marginLeft: 10,
    borderColor: "#FF5722",
    borderWidth: 1,
  },
  paperModalText: {
    fontSize: 18,
    color: "#333333",
    textAlign: "center",
    marginBottom: 20,
  },
  saveVocabButton: {
    position: "absolute",
    bottom: 30,
    right: 30,
    backgroundColor: "#2C8D81",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
  },
  saveVocabButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  default: {
    fontSize: 20,
    color: "#34495E",
    marginRight: 2,
    textAlign: "center",
  },
  highlightedWord: {
    fontSize: 18,
    color: "#FF5722",
    textDecorationLine: "underline",
  },
  underline: {
    fontSize: 20,
    color: "red",
    textDecorationLine: "underline",
    fontWeight: "bold",
  },
  discussButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 0,
    marginTop: 10,
    flexDirection: "row",
    backgroundColor: "#e3edaf",
    width: "50%",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
  },
  discussButtonText: {
    color: "#333",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
    paddingLeft: 10,
  },
  answerIndexButton: {
    // tròn
    width: 40,
    height: 40,
    borderRadius: 50,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    marginBottom: 10,
  },
  answerIndexText: {
    color: "#000",
    fontSize: 16,
    fontWeight: "600",
  },
  loadingAnimation: {
    width: 150,
    height: 150,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#8cbf26", 
  },
  audioPlayerContainer: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  albumArt: {
    width: 200,
    height: 200,
    borderRadius: 10,
  },
  albumArtPlaceholder: {
    width: 200,
    height: 200,
    borderRadius: 10,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  audioTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  playPauseButton: {
    backgroundColor: "#8cbf26",
    width: 50,
    height: 50,
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
  },
  sliderContainer: {
    width: "100%",
    alignItems: "center",
  },
  slider: {
    width: "100%",
    height: 40,
  },
  timeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 10,
  },
  timeText: {
    color: "#333",
  },
});
